[project]
name = "cc-extrator"
version = "0.1.0"
description = "Extract, translate and reinsert the text of Chrono Trigger (SNES) using Chronotools"
readme = "README.md"
authors = [
    { name = "Caio Souza", email = "bss.caio@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
cc-extrator = "cc_extrator.cli:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
